version: '3.8'

services:
  user_service:
    build: ./user_service
    ports:
      - "5001:5001"

  product_service:
    build: ./product_service
    ports:
      - "5002:5002"

  order_service:
    build: ./order_service
    ports:
      - "5003:5003"

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
